{% set name = "funcx" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/funcx-{{ version }}.tar.gz
  sha256: 24ed26caaa89a3ca08038d67d65abc05547364e4fa04ecf90f2368b10a55cce1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill =0.3.5.1
    - fair-research-login =0.2.6
    - globus-sdk >=3,<4
    - python >=3.6
    - requests >=2.20.0
    - texttable >=1.6.4,<2
    - websockets =10.3
    - six
    - packaging
    - funcx-common =0.0.15
    - tblib

test:
  imports:
    - funcx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/funcx-faas/funcx
  summary: 'funcX: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
